//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_DAPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.SanPham_Anh = new HashSet<SanPham_Anh>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public decimal GiaSP { get; set; }
        public int SoLuong { get; set; }
        public string MoTA { get; set; }
        public Nullable<int> MaKichCo { get; set; }
        public Nullable<int> MaThuongHieu { get; set; }
        public Nullable<int> MaMauSac { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual KichCo KichCo { get; set; }
        public virtual MauSac MauSac { get; set; }
        public virtual ThuongHieu ThuongHieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham_Anh> SanPham_Anh { get; set; }
    }
}
